### ISSUE TITLE
Running build display incoherent badges

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/coverage-badges-extension-plugin#16]
### Jenkins and plugins versions report

All

### What Operating System are you using (both controller, and any agents involved in the problem)?

All

### Reproduction steps

Show badges from a running build

### Expected Results

Perhaps latest successfully build ?
Perhaps new status like "computing" ?

### Actual Results

![running_code_coverage](https://github.com/jenkinsci/coverage-badges-extension-plugin/assets/825750/7780a387-02ae-40c2-9515-9ccb1d721847)

**Comment by sridamul** [comment]
Hey, @jonesbusy!
May I know how did you display the **build** status? (as shown in img)?
Cause I'm able to display **Coverages**(instructionCoverage, branchCoverage, lineCoverage), **Number of Test** and **Line of Code**

**Comment by jonesbusy** [comment]
This plugin is an extension of https://plugins.jenkins.io/embeddable-build-status/

It only provide extra placeholder to work with coverage plugin
